### ISSUE TITLE
Issue on page /src/python/us-census-geocoding.html

### ISSUE THREAD

**Issue by gischimp** [ualibweb/UALIB_ScholarlyAPI_Cookbook#51]
I believe in the coding example, latitude and longitude have been reversed.

```
latitude = response.json()['result']['addressMatches'][0]['coordinates']['x']
longitude = response.json()['result']['addressMatches'][0]['coordinates']['y']
```

Longitude should be x (Easting) and Latitude should be y (Northing).

Thanks so much for providing this repository! I love the USCB API and python and this really short-cuts bringing these together for me!

Cheers!

**Comment by vfscalfani** [comment]
Hi @gischimp.  Many thanks for the feedback and bug report. We will take a look and double check this!

@CoilSeb @MoenMi

**Comment by MoenMi** [comment]
Thanks for catching the error @gischimp!

I'm glad you find the tutorial helpful. Please let us know if you find any other issues or if there are any other APIs you would like to see covered in the Cookbook!
