### ISSUE TITLE
Making contribution

### ISSUE THREAD

**Issue by xiaohansyan** [ualibweb/UALIB_ScholarlyAPI_Cookbook#8]
I have some codes that I would like to share, is there a good way to do it? Thanks,

**Comment by vfscalfani** [comment]
Hi @xiaohansyan. Thanks for your interest!

We have not yet worked out a contributor guide (that is something we definitely need to do...). 

What are you interested in contributing? Let us know and then we can work with you on how best to move forward. 

Thanks again,

Vin

**Comment by xiaohansyan** [comment]
> 

Hi Vincent, I have written some basic Jupyter notebooks going through the steps of getting data from DPLA via its API. I also have a similar thing for LOC, but I saw there is one already in your repository, so I'd like to offer my DPLA part of the notebook. Here is the link to my GitHub page: https://github.com/xiaohansyan/LEADING2022. Please let me know what you think and if you have any feedbacks where I can further polish my codes. No worries if you decided not to use it.
